function files = plotProblem2Paper(configFile,outputDir)
%PLOTPROBLEM2PAPER 根据 Excel 方案选择生成问题二的七张论文插图。
%
% 使用方法：
%   修改：
%       结果/问题二_绘图配置.xlsx
%
%   工作表：
%       绘图设置
%
%   单元格 B2 可选择：
%       TimelinessFirst
%       MakespanFirst
%       EnergyFirst
%       TripCountFirst
%       Balanced
%
%   图片将自动添加对应中文方案后缀，例如：
%       无人机甘特图_及时性优先.png
%       无人机甘特图_完成时间优先.png
%       无人机甘特图_能耗优先.png
%       无人机甘特图_架次数优先.png
%       无人机甘特图_折中方案.png
%
%   B3 填写结果目录下的分析表文件名。
%
% 从"代码"目录运行：
%   files = problem2.plotProblem2Paper();
%
% 本程序只生成 PNG，不生成 PDF。


%% ===================== 1. 路径设置 =====================

codeDir = fileparts(fileparts(mfilename('fullpath')));
rootDir = fileparts(codeDir);

resultDir = fullfile(rootDir,'结果');


% 默认配置文件
if nargin < 1 || isempty(configFile)
    configFile = fullfile( ...
        resultDir, ...
        '问题二_绘图配置.xlsx' ...
    );
end


% 默认图片输出目录
if nargin < 2 || isempty(outputDir)
    outputDir = fullfile( ...
        rootDir, ...
        '论文', ...
        '图表', ...
        '问题二' ...
    );
end


% 如果输出文件夹不存在，则自动创建
if ~isfolder(outputDir)
    mkdir(outputDir);
end


% 检查配置文件
assert( ...
    isfile(configFile), ...
    '缺少绘图配置表：%s', ...
    configFile ...
);


%% ===================== 2. 读取绘图方案 =====================

rawChoice = readcell( ...
    configFile, ...
    'Sheet','绘图设置', ...
    'Range','B2' ...
);

choice = strtrim(string(rawChoice{1}));


% 五种方案英文名称
validNames = [ ...
    "TimelinessFirst", ...
    "MakespanFirst", ...
    "EnergyFirst", ...
    "TripCountFirst", ...
    "Balanced" ...
];


% 对应中文后缀
suffixNames = [ ...
    "及时性优先", ...
    "完成时间优先", ...
    "能耗优先", ...
    "架次数优先", ...
    "折中方案" ...
];


% 查找当前方案
idxChoice = find( ...
    choice == validNames, ...
    1 ...
);


assert( ...
    isscalar(choice) && ~isempty(idxChoice), ...
    '绘图设置!B2 中的方案名称无效：%s', ...
    choice ...
);


% 当前中文方案名称
schemeSuffix = suffixNames(idxChoice);


fprintf('\n');
fprintf('========================================\n');
fprintf('当前选择方案：%s\n',choice);
fprintf('中文方案名称：%s\n',schemeSuffix);
fprintf('========================================\n\n');


%% ===================== 3. 读取分析表文件名 =====================

rawSource = readcell( ...
    configFile, ...
    'Sheet','绘图设置', ...
    'Range','B3' ...
);

sourceName = strtrim(string(rawSource{1}));


assert( ...
    isscalar(sourceName) && strlength(sourceName) > 0, ...
    '绘图设置!B3 需要填写结果目录下的分析表文件名。' ...
);


analysisFile = fullfile( ...
    resultDir, ...
    sourceName ...
);


assert( ...
    isfile(analysisFile), ...
    '缺少问题二分析表：%s', ...
    analysisFile ...
);


%% ===================== 4. 原始数据文件 =====================

nodeFile = fullfile( ...
    rootDir, ...
    '原始题目信息', ...
    '数据', ...
    '无人机应急物资运输基础数据', ...
    '调度中心与服务区.xlsx' ...
);


demFile = fullfile( ...
    rootDir, ...
    '原始题目信息', ...
    '数据', ...
    '镇龙乡地理空间数据', ...
    '镇龙乡及周边地理数据', ...
    '数字高程模型数据（DEM）', ...
    '镇龙乡及周边30米DEM.mat' ...
);


%% ===================== 5. 读取问题二分析结果 =====================

summary = readtable( ...
    analysisFile, ...
    'Sheet','代表方案汇总' ...
);

front = readtable( ...
    analysisFile, ...
    'Sheet','Pareto前沿' ...
);

tripsAll = readtable( ...
    analysisFile, ...
    'Sheet','代表方案架次' ...
);

boxesAll = readtable( ...
    analysisFile, ...
    'Sheet','代表方案逐箱交付' ...
);


%% ===================== 6. 根据 B2 自动选择方案 =====================

trips = tripsAll( ...
    string(tripsAll.Representative) == choice, ...
    : ...
);

boxes = boxesAll( ...
    string(boxesAll.Representative) == choice, ...
    : ...
);

selected = summary( ...
    string(summary.Representative) == choice, ...
    : ...
);


assert( ...
    height(selected) == 1 && ...
    ~isempty(trips) && ...
    ~isempty(boxes), ...
    '分析表未包含方案 %s 的完整数据。', ...
    choice ...
);


assert( ...
    numel(unique(string(boxes.BoxID))) == height(boxes), ...
    '逐箱交付表存在重复货箱编号。' ...
);


assert( ...
    all(ismember( ...
        string(boxes.TripID), ...
        string(trips.TripID) ...
    )), ...
    '逐箱交付与架次表的 TripID 不一致。' ...
);


assert( ...
    abs(max(trips.Return_s) - selected.Makespan_s) < 1e-4, ...
    '架次表与方案汇总的完成时间不一致。' ...
);


assert( ...
    abs(sum(trips.Energy_kWh) - selected.Energy_kWh) < 1e-4, ...
    '架次表与方案汇总的能耗不一致。' ...
);


%% ===================== 7. 读取节点与 DEM =====================

nodes = loadNodes(nodeFile);

dem = load( ...
    demFile, ...
    'dem', ...
    'latitude', ...
    'longitude', ...
    'nodata' ...
);

dem.dem(dem.dem == dem.nodata) = NaN;


%% ===================== 8. 中文字体 =====================

oldFont = get(groot,'defaultAxesFontName');

fontCleanup = onCleanup( ...
    @()set(groot,'defaultAxesFontName',oldFont) ...
); %#ok<NASGU>

set( ...
    groot, ...
    'defaultAxesFontName', ...
    'Microsoft YaHei' ...
);


%% ===================== 9. 绘制七张图 =====================

names = { ...
    '地形路线图', ...
    '时空运输图', ...
    '逐箱时限矩阵', ...
    '电池SOC图', ...
    'Pareto权衡图', ...
    '无人机甘特图', ...
    '电池甘特图' ...
};


figures = cell(1,7);

figures{1} = drawRouteMap( ...
    trips, ...
    boxes, ...
    nodes, ...
    dem ...
);

figures{2} = drawSpaceTime( ...
    trips, ...
    boxes ...
);

figures{3} = drawDeadlineMatrix( ...
    boxes ...
);

figures{4} = drawBatterySOC( ...
    trips ...
);

figures{5} = drawPareto( ...
    front, ...
    summary, ...
    choice ...
);

figures{6} = drawDroneGantt( ...
    trips ...
);

figures{7} = drawBatteryGantt( ...
    trips ...
);


%% ===================== 10. 保存 PNG =====================

% 只保存 PNG
files = strings(7,1);


for k = 1:7

    % 文件名，例如：
    % 无人机甘特图_折中方案.png
    baseName = ...
        string(names{k}) + ...
        "_" + ...
        schemeSuffix;


    pngFile = fullfile( ...
        outputDir, ...
        baseName + ".png" ...
    );


    exportgraphics( ...
        figures{k}, ...
        pngFile, ...
        'Resolution',400, ...
        'BackgroundColor','white' ...
    );


    close(figures{k});


    files(k) = string(pngFile);

end


%% ===================== 11. 输出信息 =====================

fprintf('\n');
fprintf('========================================\n');
fprintf('问题二论文图已生成\n');
fprintf('方案英文名称：%s\n',choice);
fprintf('方案中文名称：%s\n',schemeSuffix);
fprintf('图片输出目录：%s\n',outputDir);
fprintf('========================================\n\n');

disp(files);


end


%% ========================================================================
%  读取节点
% ========================================================================

function nodes = loadNodes(path)

c = readcell( ...
    path, ...
    'Sheet','数据' ...
);

ids = string(c(:,1));


keep = ...
    ids == "O01" | ...
    ~cellfun( ...
        @isempty, ...
        regexp( ...
            cellstr(ids), ...
            '^S\d{3}$', ...
            'once' ...
        ) ...
    );


rows = c(keep,:);


nodes = table( ...
    string(rows(:,1)), ...
    zeros(size(rows,1),1), ...
    zeros(size(rows,1),1), ...
    'VariableNames', ...
    {'ID','Lon','Lat'} ...
);


for k = 1:height(nodes)

    nodes.Lon(k) = double(rows{k,3});
    nodes.Lat(k) = double(rows{k,4});

end


assert( ...
    height(nodes) == 16 && ...
    numel(unique(nodes.ID)) == 16, ...
    '节点数据需要包含 O01 和 S001 至 S015。' ...
);


end


%% ========================================================================
%  机型颜色
% ========================================================================

function color = modelColor(model)

switch string(model)

    case "A"
        color = [0.13 0.38 0.67];

    case "B"
        color = [0.02 0.55 0.49];

    case "C"
        color = [0.79 0.34 0.16];

    otherwise
        error( ...
            '未知机型：%s', ...
            string(model) ...
        );

end

end


%% ========================================================================
%  新建 Figure
% ========================================================================

function f = newFigure(width,height)

f = figure( ...
    'Visible','off', ...
    'Color','white', ...
    'Units','centimeters', ...
    'Position',[2 2 width height] ...
);

end


%% ========================================================================
%  通用坐标轴样式
% ========================================================================

function styleAxes(ax)

set( ...
    ax, ...
    'FontName','Microsoft YaHei', ...
    'FontSize',9, ...
    'LineWidth',0.8, ...
    'XColor',[0.20 0.27 0.34], ...
    'YColor',[0.20 0.27 0.34], ...
    'GridColor',[0.82 0.86 0.88], ...
    'GridAlpha',0.45, ...
    'Box','off' ...
);

end


%% ========================================================================
%  图 1：地形路线图
% ========================================================================

function f = drawRouteMap(trips,boxes,nodes,dem)

f = newFigure(23,16);

ax = axes( ...
    f, ...
    'Position',[0.10 0.11 0.74 0.81] ...
);

hold(ax,'on');


stride = 3;

elev = double( ...
    dem.dem( ...
        1:stride:end, ...
        1:stride:end ...
    ) ...
);

lon = dem.longitude(1:stride:end);
lat = dem.latitude(1:stride:end);


im = imagesc( ...
    ax, ...
    [lon(1),lon(end)], ...
    [lat(end),lat(1)], ...
    flipud(elev) ...
);


set( ...
    im, ...
    'AlphaData', ...
    double(~isnan(elev(end:-1:1,:))) * 0.88 ...
);


set(ax,'YDir','normal');

colormap(ax,terrainColors());


validElev = elev(~isnan(elev));

clim( ...
    ax, ...
    prctile(validElev,[3 97]) ...
);


padLon = 0.017;
padLat = 0.014;


xlim( ...
    ax, ...
    [ ...
        min(nodes.Lon)-padLon, ...
        max(nodes.Lon)+padLon ...
    ] ...
);


ylim( ...
    ax, ...
    [ ...
        min(nodes.Lat)-padLat, ...
        max(nodes.Lat)+padLat ...
    ] ...
);


from = strings(0,1);
to = strings(0,1);
model = strings(0,1);
count = zeros(0,1);


for k = 1:height(trips)

    stops = split( ...
        string(trips.Route(k)), ...
        "->" ...
    );

    path = [ ...
        "O01"; ...
        stops; ...
        "O01" ...
    ];


    for j = 1:numel(path)-1

        idx = find( ...
            from == path(j) & ...
            to == path(j+1) & ...
            model == string(trips.Model(k)), ...
            1 ...
        );


        if isempty(idx)

            from(end+1,1) = path(j); %#ok<AGROW>
            to(end+1,1) = path(j+1); %#ok<AGROW>

            model(end+1,1) = ...
                string(trips.Model(k)); %#ok<AGROW>

            count(end+1,1) = 1; %#ok<AGROW>

        else

            count(idx) = count(idx) + 1;

        end

    end

end


for k = 1:numel(count)

    a = find( ...
        nodes.ID == from(k), ...
        1 ...
    );

    b = find( ...
        nodes.ID == to(k), ...
        1 ...
    );


    assert( ...
        ~isempty(a) && ~isempty(b), ...
        '路线包含未知节点。' ...
    );


    dx = nodes.Lon(b) - nodes.Lon(a);
    dy = nodes.Lat(b) - nodes.Lat(a);


    c = modelColor(model(k));

    c = 0.13 + 0.87*c;


    plot( ...
        ax, ...
        [nodes.Lon(a),nodes.Lon(b)], ...
        [nodes.Lat(a),nodes.Lat(b)], ...
        'Color',c, ...
        'LineWidth',0.95 + 0.65*sqrt(count(k)) ...
    );


    midx = nodes.Lon(a) + 0.57*dx;
    midy = nodes.Lat(a) + 0.57*dy;


    quiver( ...
        ax, ...
        midx-0.045*dx, ...
        midy-0.045*dy, ...
        0.09*dx, ...
        0.09*dy, ...
        0, ...
        'Color',c, ...
        'LineWidth',1.4, ...
        'MaxHeadSize',2, ...
        'AutoScale','off' ...
    );

end


for k = 1:height(nodes)

    id = nodes.ID(k);


    if id == "O01"

        scatter( ...
            ax, ...
            nodes.Lon(k), ...
            nodes.Lat(k), ...
            210, ...
            'p', ...
            'filled', ...
            'MarkerFaceColor',[0.99 0.77 0.25], ...
            'MarkerEdgeColor',[0.15 0.20 0.27], ...
            'LineWidth',1.2 ...
        );


        text( ...
            ax, ...
            nodes.Lon(k)+0.003, ...
            nodes.Lat(k)-0.003, ...
            'O01', ...
            'FontWeight','bold', ...
            'FontSize',9, ...
            'Color',[0.12 0.18 0.23], ...
            'BackgroundColor','white', ...
            'Margin',1 ...
        );

    else

        n = sum( ...
            string(boxes.ServiceID) == id ...
        );


        scatter( ...
            ax, ...
            nodes.Lon(k), ...
            nodes.Lat(k), ...
            42+6*n, ...
            'o', ...
            'filled', ...
            'MarkerFaceColor',[0.96 0.98 0.99], ...
            'MarkerEdgeColor',[0.12 0.25 0.35], ...
            'LineWidth',1.1 ...
        );


        text( ...
            ax, ...
            nodes.Lon(k)+0.0025, ...
            nodes.Lat(k)+0.001, ...
            id, ...
            'FontSize',7.2, ...
            'Color',[0.10 0.20 0.28], ...
            'BackgroundColor','white', ...
            'Margin',0.5 ...
        );

    end

end


cb = colorbar( ...
    ax, ...
    'Position',[0.87 0.22 0.022 0.53] ...
);

cb.Label.String = '地面高程 / m';
cb.FontSize = 8;


styleAxes(ax);

grid(ax,'on');


xlabel(ax,'经度 / °E');
ylabel(ax,'纬度 / °N');

axis(ax,'equal');


handles = gobjects(1,3);

models = ["A","B","C"];


for k = 1:3

    handles(k) = plot( ...
        ax, ...
        nan, ...
        nan, ...
        'LineWidth',2.4, ...
        'Color',modelColor(models(k)) ...
    );

end


legend( ...
    ax, ...
    handles, ...
    {'A 型','B 型','C 型'}, ...
    'Location','southoutside', ...
    'Orientation','horizontal', ...
    'Box','off', ...
    'FontSize',8 ...
);


end


%% ========================================================================
%  地形配色
% ========================================================================

function cmap = terrainColors()

anchors = [ ...
    0.93 0.96 0.92; ...
    0.77 0.85 0.75; ...
    0.64 0.75 0.64; ...
    0.78 0.77 0.65; ...
    0.91 0.87 0.77 ...
];


cmap = interp1( ...
    linspace(0,1,size(anchors,1)), ...
    anchors, ...
    linspace(0,1,256) ...
);

end


%% ========================================================================
%  图 2：时空运输图
% ========================================================================

function f = drawSpaceTime(trips,boxes)

f = newFigure(24,16);

ax = axes( ...
    f, ...
    'Position',[0.11 0.13 0.84 0.80] ...
);

hold(ax,'on');


for y = 0:15

    if mod(y,2) == 0

        patch( ...
            ax, ...
            [ ...
                0, ...
                max(trips.Return_s)/3600*1.04, ...
                max(trips.Return_s)/3600*1.04, ...
                0 ...
            ], ...
            [ ...
                y-0.48, ...
                y-0.48, ...
                y+0.48, ...
                y+0.48 ...
            ], ...
            [0.96 0.98 0.99], ...
            'EdgeColor','none', ...
            'FaceAlpha',0.65 ...
        );

    end

end


for k = 1:height(trips)

    route = split( ...
        string(trips.Route(k)), ...
        "->" ...
    );


    t = [trips.Start_s(k)];
    y = [0];

    sizes = [];
    hard = [];


    for j = 1:numel(route)

        match = ...
            string(boxes.TripID) == string(trips.TripID(k)) & ...
            string(boxes.ServiceID) == route(j);


        assert( ...
            any(match), ...
            '架次 %s 在 %s 没有逐箱送达记录。', ...
            string(trips.TripID(k)), ...
            route(j) ...
        );


        values = unique( ...
            boxes.Delivery_s(match) ...
        );


        assert( ...
            max(values)-min(values) < 1e-5, ...
            '同一次投送的送达时刻不一致。' ...
        );


        t(end+1) = values(1); %#ok<AGROW>

        y(end+1) = str2double( ...
            extractAfter(route(j),1) ...
        ); %#ok<AGROW>


        sizes(end+1) = sum(match); %#ok<AGROW>

        hard(end+1) = any( ...
            isfinite(boxes.HardDeadline_s(match)) ...
        ); %#ok<AGROW>

    end


    t(end+1) = trips.Return_s(k);
    y(end+1) = 0;


    c = modelColor(trips.Model(k));

    faded = 0.20 + 0.80*c;


    plot( ...
        ax, ...
        t/3600, ...
        y, ...
        'Color',faded, ...
        'LineWidth',1.15 ...
    );


    for j = 1:numel(route)

        edge = [0.18 0.25 0.32];


        if hard(j)
            edge = [0.72 0.22 0.18];
        end


        scatter( ...
            ax, ...
            t(j+1)/3600, ...
            y(j+1), ...
            25+13*sizes(j), ...
            'o', ...
            'filled', ...
            'MarkerFaceColor',c, ...
            'MarkerEdgeColor',edge, ...
            'LineWidth',0.9 ...
        );

    end

end


xline( ...
    ax, ...
    max(trips.Return_s)/3600, ...
    ':', ...
    'Color',[0.40 0.44 0.49], ...
    'LineWidth',1.1 ...
);


ylim(ax,[-0.55 15.6]);

xlim( ...
    ax, ...
    [0 max(trips.Return_s)/3600*1.05] ...
);


yticks(ax,0:15);

yticklabels( ...
    ax, ...
    ["O01";"S"+compose('%03d',1:15)'] ...
);


styleAxes(ax);

grid(ax,'on');


xlabel(ax,'任务开始后的时间 / h');
ylabel(ax,'调度中心与服务区');


h = gobjects(1,4);

models = ["A","B","C"];


for k = 1:3

    h(k) = plot( ...
        ax, ...
        nan, ...
        nan, ...
        '-', ...
        'Color',modelColor(models(k)), ...
        'LineWidth',2 ...
    );

end


h(4) = scatter( ...
    ax, ...
    nan, ...
    nan, ...
    40, ...
    'o', ...
    'MarkerEdgeColor',[0.72 0.22 0.18] ...
);


legend( ...
    ax, ...
    h, ...
    {'A 型','B 型','C 型','含硬时限货箱的投送'}, ...
    'Location','northoutside', ...
    'Orientation','horizontal', ...
    'Box','off', ...
    'FontSize',8 ...
);


end


%% ========================================================================
%  图 3：逐箱时限矩阵
% ========================================================================

function f = drawDeadlineMatrix(boxes)

f = newFigure(25,16);

ax = axes( ...
    f, ...
    'Position',[0.085 0.13 0.77 0.78] ...
);

hold(ax,'on');


services = "S" + compose('%03d',1:15)';

counts = zeros(15,1);


for i = 1:15

    counts(i) = sum( ...
        string(boxes.ServiceID) == services(i) ...
    );

end


ncol = max(counts);


margin = nan(15,ncol);

medical = false(15,ncol);

first = false(15,ncol);

labels = strings(15,ncol);


for i = 1:15

    ix = find( ...
        string(boxes.ServiceID) == services(i) ...
    );


    target = boxes.HardDeadline_s(ix);


    target(~isfinite(target)) = ...
        boxes.ExpectedDeadline_s( ...
            ix(~isfinite(target)) ...
        );


    order = sortrows( ...
        [ ...
            (1:numel(ix))', ...
            target, ...
            -boxes.Priority(ix), ...
            boxes.Delivery_s(ix) ...
        ], ...
        [2 3 4] ...
    );


    ix = ix(order(:,1));

    target = target(order(:,1));


    for j = 1:numel(ix)

        margin(i,j) = ...
            ( ...
                target(j) - ...
                boxes.Delivery_s(ix(j)) ...
            ) / 60;


        medical(i,j) = logical( ...
            boxes.IsMedical(ix(j)) ...
        );


        first(i,j) = logical( ...
            boxes.IsFirst(ix(j)) ...
        );


        id = string( ...
            boxes.BoxID(ix(j)) ...
        );


        parts = split(id,'-');

        prefix = extractBefore( ...
            parts(2), ...
            2 ...
        );


        labels(i,j) = ...
            prefix + parts(3);

    end

end


transformed = ...
    sign(margin) .* sqrt(abs(margin));


mxNeg = max( ...
    30, ...
    ceil( ...
        max( ...
            0, ...
            -min(margin,[],'all','omitnan') ...
        ) / 15 ...
    ) * 15 ...
);


mxPos = max( ...
    60, ...
    ceil( ...
        max(margin,[],'all','omitnan') / 30 ...
    ) * 30 ...
);


set( ...
    ax, ...
    'Color',[0.94 0.95 0.96] ...
);


im = imagesc( ...
    ax, ...
    transformed, ...
    'AlphaData',~isnan(margin) ...
);


set( ...
    im, ...
    'AlphaData', ...
    double(~isnan(margin)) ...
);


clim( ...
    ax, ...
    [-sqrt(mxNeg),sqrt(mxPos)] ...
);


colormap( ...
    ax, ...
    deadlineColors( ...
        sqrt(mxNeg) / ...
        (sqrt(mxNeg)+sqrt(mxPos)) ...
    ) ...
);


for i = 1:15

    for j = 1:counts(i)

        edge = [1 1 1];

        lw = 0.9;


        if medical(i,j)

            edge = [0.70 0.20 0.20];

            lw = 1.6;

        end


        rectangle( ...
            ax, ...
            'Position',[j-0.5 i-0.5 1 1], ...
            'EdgeColor',edge, ...
            'LineWidth',lw ...
        );


        text( ...
            ax, ...
            j, ...
            i, ...
            labels(i,j), ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','middle', ...
            'FontSize',6.8, ...
            'FontWeight','bold', ...
            'Color',[0.12 0.20 0.25] ...
        );


        if first(i,j)

            plot( ...
                ax, ...
                j+0.34, ...
                i-0.33, ...
                'd', ...
                'MarkerSize',3, ...
                'MarkerFaceColor',[0.12 0.23 0.34], ...
                'MarkerEdgeColor','white', ...
                'LineWidth',0.5 ...
            );

        end

    end

end


xlim(ax,[0.5 ncol+0.5]);

ylim(ax,[0.5 15.5]);


set(ax,'YDir','reverse');


xticks(ax,1:ncol);

yticks(ax,1:15);


yticklabels(ax,services);


xlabel(ax,'服务区内货箱序号');

ylabel(ax,'服务区');


styleAxes(ax);


cb = colorbar( ...
    ax, ...
    'Position',[0.88 0.25 0.022 0.50] ...
);


tickMinutes = unique( ...
    [ ...
        -mxNeg, ...
        -30, ...
        -15, ...
        0, ...
        15, ...
        30, ...
        60, ...
        120, ...
        mxPos ...
    ] ...
);


tickMinutes = tickMinutes( ...
    tickMinutes >= -mxNeg & ...
    tickMinutes <= mxPos ...
);


cb.Ticks = ...
    sign(tickMinutes) .* ...
    sqrt(abs(tickMinutes));


cb.TickLabels = compose( ...
    '%g', ...
    tickMinutes ...
);


cb.Label.String = ...
    '送达提前量 / min';

cb.FontSize = 8;


h1 = plot( ...
    ax, ...
    nan, ...
    nan, ...
    's', ...
    'MarkerSize',8, ...
    'MarkerFaceColor','white', ...
    'MarkerEdgeColor',[0.70 0.20 0.20], ...
    'LineWidth',1.5 ...
);


h2 = plot( ...
    ax, ...
    nan, ...
    nan, ...
    'd', ...
    'MarkerSize',5, ...
    'MarkerFaceColor',[0.12 0.23 0.34], ...
    'MarkerEdgeColor','white' ...
);


legend( ...
    ax, ...
    [h1 h2], ...
    {'医疗货箱','首批保障货箱'}, ...
    'Location','southoutside', ...
    'Orientation','horizontal', ...
    'Box','off', ...
    'FontSize',8 ...
);


end


%% ========================================================================
%  时限矩阵配色
% ========================================================================

function cmap = deadlineColors(zeroPos)

x = [0 zeroPos 1];


anchor = [ ...
    0.76 0.25 0.22; ...
    0.98 0.98 0.96; ...
    0.07 0.43 0.58 ...
];


cmap = interp1( ...
    x, ...
    anchor, ...
    linspace(0,1,256), ...
    'linear' ...
);

end


%% ========================================================================
%  图 4：电池 SOC 图
% ========================================================================

function f = drawBatterySOC(trips)

f = newFigure(25,17);


tl = tiledlayout( ...
    f, ...
    3, ...
    1, ...
    'TileSpacing','compact', ...
    'Padding','compact' ...
);


models = ["A","B","C"];


tmax = max( ...
    trips.Return_s + ...
    trips.ChargeTime_s ...
) / 3600;


makespan = max( ...
    trips.Return_s ...
) / 3600;


for mi = 1:3

    ax = nexttile(tl);

    hold(ax,'on');


    modelTrips = trips( ...
        string(trips.Model) == models(mi), ...
        : ...
    );


    batteryIDs = unique( ...
        string(modelTrips.BatteryID), ...
        'stable' ...
    );


    base = modelColor(models(mi));


    legendHandles = ...
        gobjects(numel(batteryIDs),1);


    for bi = 1:numel(batteryIDs)

        b = batteryIDs(bi);


        bt = modelTrips( ...
            string(modelTrips.BatteryID) == b, ...
            : ...
        );


        bt = sortrows( ...
            bt, ...
            'Start_s' ...
        );


        shade = ...
            0.08 + ...
            0.45 * ...
            (bi-1) / ...
            max(1,numel(batteryIDs)-1);


        c = shade + (1-shade)*base;


        lastTime = 0;


        for k = 1:height(bt)

            start = bt.Start_s(k) / 3600;

            ret = bt.Return_s(k) / 3600;

            soc = bt.ReturnSOC_pct(k);

            ready = ...
                ( ...
                    bt.Return_s(k) + ...
                    bt.ChargeTime_s(k) ...
                ) / 3600;


            assert( ...
                start >= lastTime-1e-7, ...
                '电池 %s 的架次与充电重叠。', ...
                b ...
            );


            if k == 1

                plot( ...
                    ax, ...
                    [0 start], ...
                    [100 100], ...
                    '-', ...
                    'Color',c, ...
                    'LineWidth',1.3 ...
                );

            else

                plot( ...
                    ax, ...
                    [lastTime start], ...
                    [100 100], ...
                    '-', ...
                    'Color',c, ...
                    'LineWidth',1.3 ...
                );

            end


            plot( ...
                ax, ...
                [start ret], ...
                [100 soc], ...
                '--', ...
                'Color',c, ...
                'LineWidth',1.4 ...
            );


            if soc < 90-1e-8

                fastFraction = ...
                    0.65 * ...
                    (90-soc) / 90;


                totalFraction = ...
                    fastFraction + 0.35;


                t90 = ...
                    ret + ...
                    (ready-ret) * ...
                    fastFraction / ...
                    totalFraction;


                plot( ...
                    ax, ...
                    [ret t90 ready], ...
                    [soc 90 100], ...
                    '-', ...
                    'Color',c, ...
                    'LineWidth',1.5 ...
                );


                plot( ...
                    ax, ...
                    t90, ...
                    90, ...
                    'd', ...
                    'Color',c, ...
                    'MarkerFaceColor','white', ...
                    'MarkerSize',3.5, ...
                    'LineWidth',0.9 ...
                );

            else

                plot( ...
                    ax, ...
                    [ret ready], ...
                    [soc 100], ...
                    '-', ...
                    'Color',c, ...
                    'LineWidth',1.5 ...
                );

            end


            scatter( ...
                ax, ...
                ret, ...
                soc, ...
                21, ...
                'o', ...
                'filled', ...
                'MarkerFaceColor',c, ...
                'MarkerEdgeColor','white', ...
                'LineWidth',0.5 ...
            );


            lastTime = ready;

        end


        legendHandles(bi) = plot( ...
            ax, ...
            nan, ...
            nan, ...
            '-', ...
            'Color',c, ...
            'LineWidth',1.8, ...
            'DisplayName',char(b) ...
        );

    end


    yline( ...
        ax, ...
        90, ...
        ':', ...
        'Color',[0.52 0.57 0.62], ...
        'LineWidth',0.8 ...
    );


    xline( ...
        ax, ...
        makespan, ...
        ':', ...
        'Color',[0.50 0.53 0.57], ...
        'LineWidth',0.9 ...
    );


    xlim(ax,[0 tmax*1.03]);

    ylim(ax,[0 105]);


    yticks(ax,[0 25 50 75 90 100]);


    ylabel( ...
        ax, ...
        sprintf( ...
            '%s 型 SOC / %%', ...
            models(mi) ...
        ) ...
    );


    styleAxes(ax);

    grid(ax,'on');


    legend( ...
        ax, ...
        legendHandles, ...
        cellstr(batteryIDs), ...
        'Location','eastoutside', ...
        'Box','off', ...
        'FontSize',7.5 ...
    );

end


xlabel( ...
    tl, ...
    '任务开始后的时间 / h' ...
);


end


%% ========================================================================
%  图 5：Pareto 权衡图
% ========================================================================

function f = drawPareto(front,summary,choice)

f = newFigure(25,18);


tl = tiledlayout( ...
    f, ...
    2, ...
    2, ...
    'TileSpacing','compact', ...
    'Padding','compact' ...
);


x1 = front.Makespan_s / 3600;

x2 = front.Energy_kWh;

x3 = front.TripCount;

tim = front.Timeliness;


selected = summary( ...
    string(summary.Representative) == choice, ...
    : ...
);


timRange = [ ...
    min(tim), ...
    max(tim) ...
];


axesList = gobjects(1,3);


axesList(1) = nexttile(tl,1);

drawPair( ...
    axesList(1), ...
    x1, ...
    x2, ...
    x3, ...
    tim, ...
    selected.Makespan_s/3600, ...
    selected.Energy_kWh, ...
    '全部任务完成时间 / h', ...
    '运输能耗 / kWh' ...
);


axesList(2) = nexttile(tl,2);

drawPair( ...
    axesList(2), ...
    x3, ...
    tim, ...
    x3, ...
    tim, ...
    selected.TripCount, ...
    selected.Timeliness, ...
    '运输架次数', ...
    '配送及时性目标' ...
);


axesList(3) = nexttile(tl,3);

drawPair( ...
    axesList(3), ...
    x3, ...
    x2, ...
    x3, ...
    tim, ...
    selected.TripCount, ...
    selected.Energy_kWh, ...
    '运输架次数', ...
    '运输能耗 / kWh' ...
);


for i = 1:3

    colormap( ...
        axesList(i), ...
        paretoColors() ...
    );


    clim( ...
        axesList(i), ...
        timRange ...
    );

end


cb = colorbar( ...
    axesList(1), ...
    'Location','eastoutside' ...
);


cb.Label.String = ...
    '配送及时性目标';

cb.FontSize = 8;


ax = nexttile(tl,4);

hold(ax,'on');


cols = { ...
    'Timeliness', ...
    'Makespan_s', ...
    'Energy_kWh', ...
    'TripCount' ...
};


mins = [ ...
    min(tim), ...
    min(front.Makespan_s), ...
    min(x2), ...
    min(x3) ...
];


maxs = [ ...
    max(tim), ...
    max(front.Makespan_s), ...
    max(x2), ...
    max(x3) ...
];


names = string( ...
    summary.Representative ...
);


pretty = [ ...
    "及时性优先", ...
    "完成时间优先", ...
    "能耗优先", ...
    "架次数优先", ...
    "折中方案" ...
];


palette = [ ...
    0.20 0.42 0.65; ...
    0.45 0.54 0.63; ...
    0.02 0.56 0.48; ...
    0.56 0.43 0.63; ...
    0.76 0.46 0.20 ...
];


for k = 1:height(summary)

    vals = zeros(1,4);


    for j = 1:4

        vals(j) = ...
            summary.(cols{j})(k);

    end


    normed = ...
        (vals-mins) ./ ...
        max(maxs-mins,eps);


    c = palette(k,:);

    lw = 1.35;


    if names(k) == choice

        c = [0.78 0.22 0.16];

        lw = 2.8;

    end


    plot( ...
        ax, ...
        1:4, ...
        normed, ...
        '-o', ...
        'Color',c, ...
        'LineWidth',lw, ...
        'MarkerSize',4.3, ...
        'MarkerFaceColor','white', ...
        'DisplayName',char(pretty(k)) ...
    );

end


set( ...
    ax, ...
    'XTick',1:4, ...
    'XTickLabel', ...
    {'及时性','完成时间','能耗','架次数'} ...
);


xlim(ax,[0.8 4.2]);

ylim(ax,[-0.03 1.03]);


ylabel( ...
    ax, ...
    '相对损失（0 为该目标最优）' ...
);


styleAxes(ax);

grid(ax,'on');


legend( ...
    ax, ...
    'Location','eastoutside', ...
    'Box','off', ...
    'FontSize',7.3 ...
);


end


%% ========================================================================
%  Pareto 子图
% ========================================================================

function drawPair( ...
    ax, ...
    x, ...
    y, ...
    trips, ...
    tim, ...
    selectedX, ...
    selectedY, ...
    xlab, ...
    ylab ...
)

hold(ax,'on');


scatter( ...
    ax, ...
    x, ...
    y, ...
    24+5*trips, ...
    tim, ...
    'filled', ...
    'MarkerEdgeColor',[0.97 0.98 0.99], ...
    'LineWidth',0.4, ...
    'MarkerFaceAlpha',0.83 ...
);


scatter( ...
    ax, ...
    selectedX, ...
    selectedY, ...
    230, ...
    'o', ...
    'MarkerEdgeColor',[0.79 0.19 0.12], ...
    'LineWidth',1.8 ...
);


scatter( ...
    ax, ...
    selectedX, ...
    selectedY, ...
    84, ...
    'p', ...
    'filled', ...
    'MarkerFaceColor',[0.99 0.76 0.21], ...
    'MarkerEdgeColor',[0.23 0.25 0.28], ...
    'LineWidth',0.8 ...
);


xlabel(ax,xlab);

ylabel(ax,ylab);


styleAxes(ax);

grid(ax,'on');


end


%% ========================================================================
%  Pareto 配色
% ========================================================================

function cmap = paretoColors()

anchor = [ ...
    0.09 0.45 0.57; ...
    0.42 0.69 0.72; ...
    0.95 0.77 0.42; ...
    0.76 0.30 0.19 ...
];


cmap = interp1( ...
    linspace(0,1,size(anchor,1)), ...
    anchor, ...
    linspace(0,1,256) ...
);

end


%% ========================================================================
%  甘特图机型颜色
% ========================================================================

function c = ganttModelColor(model)

switch string(model)

    case "A"

        c = [76 114 176] / 255;

    case "B"

        c = [221 132 82] / 255;

    case "C"

        c = [85 168 104] / 255;

    otherwise

        error( ...
            '未知机型：%s', ...
            string(model) ...
        );

end

end


%% ========================================================================
%  图 6：无人机甘特图
% ========================================================================

function f = drawDroneGantt(trips)

f = newFigure(28,14);


ax = axes( ...
    f, ...
    'Position',[0.105 0.20 0.87 0.76] ...
);

hold(ax,'on');


ids = sort( ...
    unique(string(trips.DroneID)), ...
    'ascend' ...
);


barHeight = 0.62;


for i = 1:numel(ids)

    rows = find( ...
        string(trips.DroneID) == ids(i) ...
    );


    [~,order] = sort( ...
        trips.Start_s(rows) ...
    );


    rows = rows(order);


    for k = rows'

        start = ...
            trips.Start_s(k) / 3600;


        stop = ...
            trips.Return_s(k) / 3600;


        rectangle( ...
            ax, ...
            'Position',[ ...
                start, ...
                i-barHeight/2, ...
                stop-start, ...
                barHeight ...
            ], ...
            'FaceColor', ...
            ganttModelColor(trips.Model(k)), ...
            'EdgeColor','white', ...
            'LineWidth',1.0 ...
        );


        route = strrep( ...
            string(trips.Route(k)), ...
            "->", ...
            "-" ...
        );


        text( ...
            ax, ...
            (start+stop)/2, ...
            i, ...
            route, ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','middle', ...
            'Color','white', ...
            'FontSize',8, ...
            'FontWeight','normal', ...
            'Clipping','on' ...
        );

    end

end


makespan = ...
    max(trips.Return_s) / 3600;


finishGanttAxes( ...
    ax, ...
    ids, ...
    makespan, ...
    makespan, ...
    '无人机', ...
    '路线' ...
);


ylabels = strings(size(ids));


for i = 1:numel(ids)

    m = string( ...
        trips.Model( ...
            find( ...
                string(trips.DroneID) == ids(i), ...
                1 ...
            ) ...
        ) ...
    );


    ylabels(i) = ...
        ids(i) + "(" + m + ")";

end


yticklabels( ...
    ax, ...
    ylabels ...
);


addGanttLegend( ...
    ax, ...
    makespan, ...
    false ...
);


end


%% ========================================================================
%  图 7：电池甘特图
% ========================================================================

function f = drawBatteryGantt(trips)

f = newFigure(28,19);


ax = axes( ...
    f, ...
    'Position',[0.105 0.16 0.87 0.81] ...
);

hold(ax,'on');


ids = sort( ...
    unique(string(trips.BatteryID)), ...
    'ascend' ...
);


barHeight = 0.62;


for i = 1:numel(ids)

    rows = find( ...
        string(trips.BatteryID) == ids(i) ...
    );


    [~,order] = sort( ...
        trips.Start_s(rows) ...
    );


    rows = rows(order);


    previousReady = 0;


    for k = rows'

        start = ...
            trips.Start_s(k) / 3600;


        stop = ...
            trips.Return_s(k) / 3600;


        ready = ...
            ( ...
                trips.Return_s(k) + ...
                trips.ChargeTime_s(k) ...
            ) / 3600;


        assert( ...
            start >= previousReady-1e-7, ...
            '电池 %s 的执行与充电时段重叠。', ...
            ids(i) ...
        );


        rectangle( ...
            ax, ...
            'Position',[ ...
                start, ...
                i-barHeight/2, ...
                stop-start, ...
                barHeight ...
            ], ...
            'FaceColor', ...
            ganttModelColor(trips.Model(k)), ...
            'EdgeColor','white', ...
            'LineWidth',1.0 ...
        );


        if stop-start >= 0.14

            text( ...
                ax, ...
                (start+stop)/2, ...
                i, ...
                string(trips.TripID(k)), ...
                'HorizontalAlignment','center', ...
                'VerticalAlignment','middle', ...
                'Color','white', ...
                'FontSize',7.4, ...
                'Clipping','on' ...
            );

        end


        if ready > stop+1e-9

            rectangle( ...
                ax, ...
                'Position',[ ...
                    stop, ...
                    i-barHeight/2, ...
                    ready-stop, ...
                    barHeight ...
                ], ...
                'FaceColor',[0.82 0.85 0.88], ...
                'EdgeColor','white', ...
                'LineWidth',1.0 ...
            );


            if ready-stop >= 0.16

                text( ...
                    ax, ...
                    (stop+ready)/2, ...
                    i, ...
                    '充电', ...
                    'HorizontalAlignment','center', ...
                    'VerticalAlignment','middle', ...
                    'Color',[0.25 0.31 0.36], ...
                    'FontSize',7.3, ...
                    'Clipping','on' ...
                );

            end

        end


        previousReady = ready;

    end

end


makespan = ...
    max(trips.Return_s) / 3600;


rightEdge = ...
    max( ...
        trips.Return_s + ...
        trips.ChargeTime_s ...
    ) / 3600;


finishGanttAxes( ...
    ax, ...
    ids, ...
    rightEdge, ...
    makespan, ...
    '共享电池', ...
    '架次' ...
);


addGanttLegend( ...
    ax, ...
    makespan, ...
    true ...
);


end


%% ========================================================================
%  甘特图坐标轴
% ========================================================================

function finishGanttAxes( ...
    ax, ...
    ids, ...
    rightEdge, ...
    makespan, ...
    yLabel, ...
    ~ ...
)


ylim( ...
    ax, ...
    [0.45 numel(ids)+0.55] ...
);


xlim( ...
    ax, ...
    [0 rightEdge+0.12] ...
);


yticks( ...
    ax, ...
    1:numel(ids) ...
);


yticklabels( ...
    ax, ...
    ids ...
);


% 首批硬时限：1 h
xline( ...
    ax, ...
    1, ...
    '--', ...
    'Color',[0.77 0.30 0.32], ...
    'LineWidth',1.8 ...
);


% 整个方案完成时间
xline( ...
    ax, ...
    makespan, ...
    ':', ...
    'Color',[0.51 0.45 0.70], ...
    'LineWidth',2.0 ...
);


xlabel( ...
    ax, ...
    '任务时间 / h' ...
);


ylabel( ...
    ax, ...
    yLabel ...
);


set( ...
    ax, ...
    'FontName','Microsoft YaHei', ...
    'FontSize',10, ...
    'LineWidth',0.9, ...
    'Box','on', ...
    'XGrid','on', ...
    'YGrid','off', ...
    'GridColor',[0.70 0.73 0.77], ...
    'GridAlpha',0.25, ...
    'XColor',[0.13 0.16 0.20], ...
    'YColor',[0.13 0.16 0.20] ...
);


end


%% ========================================================================
%  甘特图图例
% ========================================================================

function addGanttLegend( ...
    ax, ...
    makespan, ...
    includeCharge ...
)


handles = gobjects(0,1);

labels = {};


for model = ["A","B","C"]

    handles(end+1) = patch( ...
        ax, ...
        nan, ...
        nan, ...
        ganttModelColor(model), ...
        'EdgeColor','none' ...
    ); %#ok<AGROW>


    labels{end+1} = ...
        char(model+" 型"); %#ok<AGROW>

end


% 电池甘特图增加"充电"图例
if includeCharge

    handles(end+1) = patch( ...
        ax, ...
        nan, ...
        nan, ...
        [0.82 0.85 0.88], ...
        'EdgeColor','none' ...
    ); %#ok<AGROW>


    labels{end+1} = ...
        '充电'; %#ok<AGROW>

end


% 首批硬时限
handles(end+1) = plot( ...
    ax, ...
    nan, ...
    nan, ...
    '--', ...
    'Color',[0.77 0.30 0.32], ...
    'LineWidth',1.8 ...
); %#ok<AGROW>


labels{end+1} = ...
    '首批硬时限 1 h';


% 完成时间
handles(end+1) = plot( ...
    ax, ...
    nan, ...
    nan, ...
    ':', ...
    'Color',[0.51 0.45 0.70], ...
    'LineWidth',2.0 ...
); %#ok<AGROW>


labels{end+1} = sprintf( ...
    '完成时间 %.2f h', ...
    makespan ...
);


legend( ...
    ax, ...
    handles, ...
    labels, ...
    'Location','southoutside', ...
    'Orientation','horizontal', ...
    'Box','off', ...
    'FontSize',8.5 ...
);


end