function writeDiagnostics(result,analysisFile)
%WRITEDIAGNOSTICS 从运行记录重建诊断表，支持不重新搜索的报告生成。
config = result.Config;
warm = result.Diagnostics.WarmStart;
referenceLabel = '配置参考完成时间（s）';
referenceTime_s = config.BaselineMakespan_s;
if ~isempty(result.SeedDiagnostics)
    referenceLabel = '初始档案最快完成时间（s）';
    referenceTime_s = min(result.SeedDiagnostics.Makespan_s);
elseif warm.Enabled
    referenceLabel = '外部初始解完成时间（s）';
    referenceTime_s = warm.InitialObjectives.Makespan_s;
end
diagnostics = {'指标','数值'; ...
    '质量容量简单下界（趟）',result.Diagnostics.MassLowerBound; ...
    '体积容量简单下界（趟）',result.Diagnostics.VolumeLowerBound; ...
    '本次各轮初始方案最少架次数（趟）',result.Diagnostics.PackingSeedTripCount; ...
    referenceLabel,referenceTime_s; ...
    '本次最快完成时间（s）',result.Diagnostics.BestMakespan_s; ...
    '搜索总耗时上限（s）',config.TimeLimit_s; ...
    '实际搜索及初始化耗时（s）',result.SearchElapsed_s; ...
    '初始档案路径',char(config.SeedArchiveFile); ...
    '初始档案方案数',height(result.SeedDiagnostics); ...
    '外部热启动已启用',warm.Enabled};
if warm.Enabled
    diagnostics = [diagnostics; { ...
        '外部架次文件',char(warm.TripFile); ...
        '外部逐箱文件',char(warm.DeliveryFile); ...
        '导入架次数',warm.ImportedTripCount; ...
        '导入货箱数',warm.ImportedBoxCount; ...
        '重排程初始解可行',warm.InitialFeasible; ...
        '重排程初始及时性目标',warm.InitialObjectives.Timeliness; ...
        '重排程初始完成时间（s）',warm.InitialObjectives.Makespan_s; ...
        '重排程初始总能耗（kWh）',warm.InitialObjectives.Energy_kWh; ...
        '重排程初始架次数',warm.InitialObjectives.TripCount; ...
        '外部排程字段处理',char(warm.SchedulingFields)}];
    writetable(warm.InitialValidation,analysisFile,'Sheet','外部热启动校核','Range','A1');
end
writecell(diagnostics,analysisFile,'Sheet','求解诊断','Range','A1');
end
