function input = loadInput(config)
%LOADINPUT 读取并独立核对问题三折中方案与原始资源库存。
p=common.projectPaths();
if ~isfield(config,'ArchiveFile') || isempty(config.ArchiveFile)
    config.ArchiveFile=fullfile(p.ResultDir,'问题三_Pareto完整档案.mat');
end
if ~isfield(config,'SubmissionFile') || isempty(config.SubmissionFile)
    config.SubmissionFile=fullfile(p.ResultDir,'问题三_结果提交_折中方案.xlsx');
end
if ~isfield(config,'TemplateFile') || isempty(config.TemplateFile)
    config.TemplateFile=p.TemplateFile;
end
assert(isfile(config.ArchiveFile) && isfile(config.SubmissionFile), ...
    '缺少问题三完整档案或折中方案提交簿。');
raw=load(config.ArchiveFile,'saved');
assert(isfield(raw,'saved') && isfield(raw.saved,'Representatives') && ...
    isfield(raw.saved.Representatives,'Balanced'), ...
    '问题三档案缺少折中主方案。');
rep=raw.saved.Representatives.Balanced;
assert(rep.Validation.Feasible && all(rep.Validation.Checks.Passed), ...
    '问题三折中方案没有通过原有校核。');
assert(height(rep.Transport.Trips)==22 && ...
    height(rep.Transport.Deliveries)==80 && ...
    height(rep.Relay.RelayTrips)==3, ...
    '问题三折中方案任务数量与已确认基线不符。');
check=problem3.verifySubmission(rep,config.SubmissionFile,config.TemplateFile);
assert(check.Feasible,'问题三档案与折中方案提交簿不一致：%s', ...
    strjoin(check.Checks.Sheet(~check.Checks.Passed),','));
data=problem3.loadData(struct());
assert(all(ismember(rep.Transport.Deliveries.BoxID,data.Boxes.BoxID)) && ...
    numel(unique(rep.Transport.Deliveries.BoxID))==height(data.Boxes), ...
    '问题三货箱与原始清单不一致。');
val=problem3.validateProblem3(rep,data,struct());
assert(val.Feasible,'问题三主方案重新校核失败：%s', ...
    strjoin(val.Checks.Check(~val.Checks.Passed),','));
input=struct('Rep',rep,'Data',data,'ArchiveFile',string(config.ArchiveFile), ...
    'SubmissionFile',string(config.SubmissionFile),'SourceCheck',check, ...
    'BaselineCheck',val);
end
